---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - domains/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - domains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - routes/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.laf.dev
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.laf.dev
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.laf.dev
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
