apiVersion: instance.laf.dev/v1
kind: Instance
metadata:
  name: test
  namespace: testing-app-creation
spec:
  region: testing-instance-region
  appid: test-appid
  state: Running
  bundle:
    displayName: "Standard"
    requestCPU: "500m"
    requestMemory: "128Mi"
    limitCPU: "1000m"
    limitMemory: "256Mi"
    databaseCapacity: "1Gi"
    storageCapacity: "1Gi"
    networkTrafficOutbound: "1Gi"
    priority: 10
  runtime:
    type: node:laf
    image:
      main: "nginx"
    version:
      version: 0.8.7