---
kind: Service
apiVersion: v1
metadata:
  name: oss
#  namespace: laf
spec:
  selector:
    app: oss
  clusterIP: None
  ports:
    - port: 9000
      targetPort: 9000
      name: http
    - port: 9001
      targetPort: 9001
      name: console


### This oss ONLY work for demo purpose, you should config your own volume for production use!
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oss
#  namespace: laf
  labels:
    app: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss
  serviceName: "oss"
  template:
    metadata:
      labels:
        app: oss
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: minio/minio:RELEASE.2022-08-13T21-54-44Z
          name: oss
          env:
            - name: MINIO_ROOT_USER
              value: minio-root-user
            - name: MINIO_ROOT_PASSWORD
              value: minio-root-password
            - name: MINIO_REGION_NAME
              value: default
          command: ["minio", "server", "/data/{0...3}", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always