apiVersion: oss.laf.dev/v1
kind: Store
metadata:
  name: store-sample
spec:
  provider: minio
  endpoint: localhost:9000
  accessKey: minio-root-user
  secretKey: minio-root-password
  region: default
  priority: 10
  useSSL: false
  capacity:
    storage: 10Gi
    objectCount: 10000
    userCount: 1000
    bucketCount: 2000

