# permissions for end users to edit osses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oss-editor-role
rules:
- apiGroups:
  - oss.laf.dev
  resources:
  - osses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.laf.dev
  resources:
  - osses/status
  verbs:
  - get
