

---
apiVersion: database.laf.dev/v1
kind: Store
metadata:
  name: store-sample
#  namespace: laf-system
spec:
  provider: mongodb
  region: default
  connectionUri: mongodb://root:password123@mongo.default:27017/?authSource=admin
  capacity:
    userCount: 1000
    storage: 100Gi
    databaseCount: 1000
    collectionCount: 10000