apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-auth.fullname" . }}
  labels:
    {{- include "service-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "service-auth.selectorLabels" . | nindent 4 }}
