# permissions for end users to edit functions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-editor-role
rules:
- apiGroups:
  - runtime.laf.dev
  resources:
  - functions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runtime.laf.dev
  resources:
  - functions/status
  verbs:
  - get
