apiVersion: gateway.laf.dev/v1
kind: Domain
metadata:
  name: domain-sample
spec:
  domain: app.laf.win
  backendType: app
  region: default
  cluster:
    url: http://localhost:19180/apisix/admin
    key: edd1c9f034335f136f87ad84b625c8f1