# permissions for end users to view domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domain-viewer-role
rules:
- apiGroups:
  - gateway.laf.dev
  resources:
  - domains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - domains/status
  verbs:
  - get
