# permissions for end users to view routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-viewer-role
rules:
- apiGroups:
  - gateway.laf.dev
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - routes/status
  verbs:
  - get
