---
apiVersion: v1
kind: ConfigMap
metadata:
  name: casdoor-config
  namespace: sealos
data:
  app.conf: |-
    appname = casdoor
    httpport = 8000
    runmode = dev
    SessionOn = true
    copyrequestbody = true
    driverName = postgres
    dataSourceName = ${DATA_SOURCE_NAME}
    # dataSourceName = "user=postgres password=123456 host=pgdb port=5432 sslmode=disable dbname=casdoor"
    dbName =
    tableNamePrefix =
    showSql = false
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = "casdoor"
    socks5Proxy = "127.0.0.1:10808"
    verificationCodeTimeout = 10
    initScore = 2000
    logPostOnly = true
    origin =
    staticBaseUrl = ""
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor
  namespace: sealos
  labels:
    app: casdoor
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30800
  selector:
    app: casdoor


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: sealos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-server
          image: casbin/casdoor:v1.143.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "./server --createDatabase=true"]
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: casdoor-conf-volume
              mountPath: /conf/app.conf
              subPath: app.conf
          env:
            - name: RUNNING_IN_DOCKER
              value: "true"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: DATA_SOURCE_NAME
              value: "user=postgres password=123456 host=pgdb port=5432 sslmode=disable dbname=casdoor"
      volumes:
        - name: casdoor-conf-volume
          configMap:
            name: casdoor-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor-local-cdn
  namespace: sealos
spec:
  selector:
    matchLabels:
      app: casdoor-local-cdn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: casdoor-local-cdn
    spec:
      containers:
        - name: docker-casbin
          image: labring/docker-casbin:main
          ports:
            - containerPort: 8080
              name: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: casdoor-local-cdn
  namespace: sealos
  labels:
    app: casdoor-local-cdn
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: casdoor-local-cdn
