name: Build Controllers Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main", "fix-workflow"]
    paths:
      - "controllers/**"
      - ".github/workflows/build_controllers.yml"
      - "charts/**"
      - ".github/workflows/build_cluster_image.yml"
      - "deploy/Kubefile"
      - "!**/*.md"
      
env:
  # Common versions
  GO_VERSION: "1.19"

jobs:
  controllers-build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        module: [ application, database, gateway, instance, oss, runtime ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build ${{ matrix.module }} amd64 & arm64
        working-directory: controllers/${{ matrix.module }}
        run: |
          make build
          chmod +x bin/manager-amd64
          chmod +x bin/manager-arm64

      - name: Prepare
        id: prepare
        run: |
          TAG=dev
          echo ::set-output name=tag_name::${TAG}

      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          version: latest

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and publish) ${{ matrix.module }} main image
        env:
          # fork friendly ^^
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/laf-${{ matrix.module }}-controller
        working-directory: controllers/${{ matrix.module }}
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t ${DOCKER_REPO}:${{ steps.prepare.outputs.tag_name }} \
          -f Dockerfile \
          .

  trigger-workflow-cluster-image:
    needs: [ controllers-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cluster image workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: controllers_build_success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'