name: dockerize-runtime-exporter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "services/runtime-exporter/**"
      - ".github/workflows/dockerize-runtime-exporter.yml"
      - "!**/*.md"
      - "!services/runtime-exporter/package-lock.json"

concurrency:
  group: dockerize-runtime-exporter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize-runtime-exporter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/runtime-exporter
            docker.io/${{ secrets.DOCKER_USERNAME }}/runtime-exporter
          # https://github.com/docker/metadata-action#typesemver
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/runtime-exporter
          file: ./services/runtime-exporter/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64

  trigger-workflow-build-cluster-image:
    needs: [dockerize-runtime-exporter]
    runs-on: ubuntu-latest
    steps:
      - name: trigger cluster image workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: docker_build_success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "latest"}'
