name: dockerize-web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/dockerize-web.yml'
      - '!**/*.md'
      - '!web/package-lock.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: web/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/package-lock.json') }}

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Package
        working-directory: web
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build web
        working-directory: web
        env:
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          VITE_GITHUB_SHA: ${{ github.sha }}
        run: npm run build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        if: ${{ !github.event.repository.fork }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          sourcemaps: web/dist/assets
          url_prefix: '~/assets/'
          version: ${{ format('laf@{0}', github.sha) }}

      - run: |
          rm -rf web/dist/assets/*.map

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/laf-web
            docker.io/${{ secrets.DOCKER_USERNAME }}/laf-web
          # https://github.com/docker/metadata-action#typesemver
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64

  trigger-workflow-build-cluster-image:
    needs: [dockerize-web]
    runs-on: ubuntu-latest
    steps:
      - name: trigger cluster image workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: docker_build_success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "latest"}'
