name: dockerize-controllers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "core/controllers/**"
      - ".github/workflows/dockerize-controllers.yml"
      - "!**/*.md"

env:
  # Common versions
  GO_VERSION: "1.19"

concurrency:
  group: dockerize-${{ github.ref }}

jobs:
  dockerize-controllers:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        module: [database, gateway, oss]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Build ${{ matrix.module }} amd64 & arm64
        working-directory: core/controllers/${{ matrix.module }}
        run: |
          make build
          chmod +x bin/manager-amd64
          chmod +x bin/manager-arm64

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/laf-${{ matrix.module }}-controller
            docker.io/${{ secrets.DOCKER_USERNAME }}/laf-${{ matrix.module }}-controller
          # https://github.com/docker/metadata-action#typesemver
          tags: |
            type=edge,enable=true,branch=main,value=latest
            type=sha,enable=true,format=short

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./core/controllers/${{ matrix.module }}
          file: ./core/controllers/${{ matrix.module }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64


  trigger-workflow-build-cluster-image:
    needs: [dockerize-controllers]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cluster image workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: docker_build_success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "latest"}'
