# permissions for end users to view bundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bundle-viewer-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - bundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - bundles/status
  verbs:
  - get
