# permissions for end users to view creationforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: creationform-viewer-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms/status
  verbs:
  - get
