# permissions for end users to edit creationforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: creationform-editor-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms/status
  verbs:
  - get
