---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - bundles/finalizers
  verbs:
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - bundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms/finalizers
  verbs:
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - creationforms/status
  verbs:
  - get
  - patch
  - update
