# permissions for end users to edit runtimepackages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimepackage-editor-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - runtimepackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - runtimepackages/status
  verbs:
  - get
