# permissions for end users to view triggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trigger-viewer-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - triggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - triggers/status
  verbs:
  - get
